### ISSUE TITLE
Remove developer list section in pom

### ISSUE THREAD

**Issue by jnioche** [apache/incubator-stormcrawler#1179]
Add Tim, remove Jorge Luis Betancourt who has not contributed in recent years and is not on the PMC

**Comment by ayushtkn** [comment]
not sure how fancy is the approach to keep on maintaining the pom.xml with developer names, I have seen usually the names being maintained on the website of the project.

**Comment by rzo1** [comment]
> not sure how fancy is the approach to keep on maintaining the pom.xml with developer names, I have seen usually the names being maintained on the website of the project.

We just removed it in Storm recently; imho we can omit this section here too because it is cumbersome to maintain and the information will be accessible by looking into the project's roaster.

**Comment by dave2wave** [comment]
I agree. Really the project (PMC) as a whole is always the responsible developer. The committee members and committers are trusted by the PMC as a whole. Putting the developers names in poms and such that will be part of a release may expose these individuals when as a whole the PMC is within the "Legal Shield" of the ASF.

Having a list on the website (or the PMC keeping one) can be helpful in order to sort out names, emails, apache ids, and GitHub ids. It can get confusing who is saying what. If the list is public then it's fair to make it be opt-in.

**Comment by jnioche** [comment]
Thanks everyone for your comments. This section made sense when the project was outside ASF but not anymore.
I have removed it in #1181
